"""initial schema

Revision ID: 43fc3e92705f
Revises: 
Create Date: 2026-07-12 03:57:58.565460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.entities.guid


revision: str = '43fc3e92705f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', src.entities.guid.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('files',
    sa.Column('id', src.entities.guid.GUID(), nullable=False),
    sa.Column('owner_id', src.entities.guid.GUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_links',
    sa.Column('id', src.entities.guid.GUID(), nullable=False),
    sa.Column('owner_id', src.entities.guid.GUID(), nullable=False),
    sa.Column('file_id', src.entities.guid.GUID(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'DOWNLOAD', 'EDIT', name='linkpermission', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'EXPIRED', 'REVOKED', name='linkstatus', native_enum=False, length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_protected', sa.Boolean(), nullable=False),
    sa.Column('allow_download', sa.Boolean(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('expiry_warning_sent', sa.Boolean(), nullable=False),
    sa.Column('expired_notice_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_logs',
    sa.Column('id', src.entities.guid.GUID(), nullable=False),
    sa.Column('shared_link_id', src.entities.guid.GUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shared_link_id'], ['shared_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', src.entities.guid.GUID(), nullable=False),
    sa.Column('user_id', src.entities.guid.GUID(), nullable=False),
    sa.Column('shared_link_id', src.entities.guid.GUID(), nullable=True),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'EXPIRED', name='notificationtype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shared_link_id'], ['shared_links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('access_logs')
    op.drop_table('shared_links')
    op.drop_table('files')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
