"""update user authentication fields

Revision ID: a67f60ae991e
Revises: b6b8c2e15b7d
Create Date: 2026-08-13 19:34:34.318485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a67f60ae991e'
down_revision: Union[str, None] = 'b6b8c2e15b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_codes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'mfa_recovery_codes')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
