name: Deploy TrustShare to AWS

on:
  push:
    branches:
      - Group-B-feature/Deployment-Shashank

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |

            cd ~/secure-file-sharing-07-26

            git checkout Group-B-feature/Deployment-Shashank

            git pull origin Group-B-feature/Deployment-Shashank

            docker compose down

            docker compose up -d --build